run_name: simple_mlp

seed: 42

# Train / val / test split ratios
val_rate: 0.1
test_rate: 0.1

# Model configuration
model_type: mlp               # options: "mlp", "cnn_gru"
hidden_dim: 512
nb_hidden: 4

# Training configuration
epochs: 20
batch_size: 512 
lr: 0.0005
device: mps             # options: "cpu", "mps", "cuda"
