run_name: cnn

seed: 42

# Train / val / test split ratios
val_rate: 0.1
test_rate: 0.1

# Model configuration
model_type: cnn

# for the simple mlp
mlp_hidden_dim: 512
mlp_nb_hidden: 4

# for the dilated cnn
cnn_channels: 64
cnn_blocks: 6
cnn_kernel_size: 3
cnn_head_hidden: 128

# Training configuration
epochs: 20
batch_size: 512 
lr: 0.0005
device: mps             # options: "cpu", "mps", "cuda"
